In [28]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn
import sklearn.ensemble

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [30]:
train = pd.read_csv(r"C:\Users\DELL\Desktop\projects\Music data\train.csv")
train = train.fillna(0)
#print(train.head(5))


test = pd.read_csv(r"C:\Users\DELL\Desktop\projects\Music data\test.csv")
test = test.fillna(0)
print(test.head(5))

       Artist Name                                Track Name  Popularity  \
0      David Bowie              Space Oddity - 2015 Remaster        73.0   
1      Crimson Sun                       Essence of Creation        34.0   
2             P!nk                          Raise Your Glass        78.0   
3     Shawn Mendes                                    Wonder        80.0   
4  Backstreet Boys  Helpless When She Smiles - Radio Version        48.0   

   danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.310   0.403   0.0   -13.664     1       0.0326       0.07260   
1         0.511   0.955   1.0    -5.059     1       0.1290       0.00040   
2         0.700   0.709   7.0    -5.006     1       0.0839       0.00480   
3         0.333   0.637   1.0    -4.904     0       0.0581       0.13100   
4         0.393   0.849  11.0    -4.114     1       0.0459       0.00421   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0          0.00

In [31]:
df_test = test
del df_test["Artist Name"]
del df_test["Track Name"]
print(df_test.head(2))

   Popularity  danceability  energy  key  loudness  mode  speechiness  \
0        73.0         0.310   0.403  0.0   -13.664     1       0.0326   
1        34.0         0.511   0.955  1.0    -5.059     1       0.1290   

   acousticness  instrumentalness  liveness  valence    tempo  \
0        0.0726          0.000093     0.139    0.466  134.480   
1        0.0004          0.000009     0.263    0.291  151.937   

   duration_in min/ms  time_signature  
0            318027.0               4  
1            220413.0               4  


In [32]:
df_train = train
genre = df_train.pop("Class") 
del df_train["Artist Name"]
del df_train["Track Name"]
print(df_train.head(5))

   Popularity  danceability  energy   key  loudness  mode  speechiness  \
0        60.0         0.854   0.564   1.0    -4.964     1       0.0485   
1        54.0         0.382   0.814   3.0    -7.230     1       0.0406   
2        35.0         0.434   0.614   6.0    -8.334     1       0.0525   
3        66.0         0.853   0.597  10.0    -6.528     0       0.0555   
4        53.0         0.167   0.975   2.0    -4.279     1       0.2160   

   acousticness  instrumentalness  liveness  valence    tempo  \
0      0.017100          0.000000    0.0849   0.8990  134.071   
1      0.001100          0.004010    0.1010   0.5690  116.454   
2      0.486000          0.000196    0.3940   0.7870  147.681   
3      0.021200          0.000000    0.1220   0.5690  107.033   
4      0.000169          0.016100    0.1720   0.0918  199.060   

   duration_in min/ms  time_signature  
0            234596.0               4  
1            251733.0               4  
2            109667.0               4  
3   

In [33]:
model = sklearn.ensemble.RandomForestClassifier()
model.fit(df_train, genre)

RandomForestClassifier()

In [34]:
pred = model.predict(test)
pred = pred.ravel()
print(pred)

[10  8  9 ...  9  6  5]


In [35]:
pred_one_hot = np.eye(11)[pred]
print(pred_one_hot)
type(pred_one_hot)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


numpy.ndarray

In [37]:
result = pd.DataFrame(pred_one_hot)
result.to_csv(r'C:\Users\DELL\Desktop\projects\Music data\mysubmissionfile.csv', index=False)